name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate all HTML files
        uses: Cyb3r-Jak3/html5validator-action@v8.0.0
        with:
          root: .
          ignore_warnings: true  # optional, depending on your needs

      - name: Deploy to GitHub Pages
        if: ${{ success() }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
