name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Validate all HTML files
      - name: Validate all HTML files
        uses: Cyb3r-Jak3/html5validator-action@v8.0.0
        with:
          root: .

      # 3️⃣ Deploy to GitHub Pages only if HTML is valid
      - name: Deploy to GitHub Pages
        if: ${{ success() }}
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./   # deploy the repository root
