name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # Required for proper gh-pages deployment

      # 2️⃣ Validate all HTML files
      - name: Validate all HTML files
        uses: Cyb3r-Jak3/html5validator-action@v8.0.0
        with:
          root: .
          ignore_warnings: true   # optional: don't fail workflow on minor warnings

      # 3️⃣ Deploy to GitHub Pages only if HTML validation succeeds
      - name: Deploy to GitHub Pages
        if: ${{ success() }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./          # directory to deploy
          publish_branch: gh-pages # optional, specify the branch for GitHub Pages
